version: '3.8'

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: dbsales
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: dbsales
      DB_USERNAME: root
      DB_PASSWORD: toor
    depends_on:
      - db
    volumes:
      - .:/var/www
    command: sh -c "/usr/local/bin/wait-for-it.sh db:3306 -- php artisan migrate --force && php -S 0.0.0.0:8000 -t public"

volumes:
  mysql_data:
